### ISSUE TITLE
The mixed type can be replaced with array

### ISSUE THREAD

**Issue by pamparam83** [yiisoft/form-model#21]
in this method I think you can change the mix type to an array

https://github.com/yiisoft/form-model/blob/daa51d3791c662acbe52e71258a068e801a2fbfc/src/FormHydrator.php#L41-L51

**Comment by vjik** [comment]
In most cases data for form model popalting:
- used once and not need after populating;
- come from the user, and can be any type (for example, `ServerRequestInterface::getParsedBody()` returns `array|object|null`).

Goal of this method — for incorrect data returns false, not throw exception or error.
